name: menu_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  get_it: ^8.0.3
  image_picker: ^1.1.2
  mime: ^2.0.0
  no_screenshot: ^0.3.1
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/menu.png

flutter_icons:
  android: true
  image_path: "assets/icons/menu.png" # Path to your icon image
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF" # Background color for Android adaptive icons
  # adaptive_icon_foreground: "assets/icons/icon_foreground.png"  # Uncomment if you have separate foreground
  remove_alpha_ios: true # Removes transparency for iOS if needed
  web:
    generate: true
    image_path: "assets/icons/menu.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/menu.png"
  macos:
    generate: true
    image_path: "assets/icons/menu.png"
